apiVersion: v1
kind: Deployment
metadata:
  name: frontend-pod
spec:
  replicas: 3

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: forwardzhe/k8s-frontend:1.0
          ports:
            - containerPort: 80